### ISSUE TITLE
Missing zone files

### ISSUE THREAD

**Issue by amnesia033** [cmsj/addon-bind#18]
Hi,

After installation and initial configuration, everything runs fine. I can see the zones being transferred, but zone files are not created in the /zone/ directory. Here's the error I can see in the log:

dumping master file: /addon_configs/de554ef4_bind/zones/tmp-JyBFoNDYrQ: open: file not found

Resolving works fine, so it looks as it just caches the zone data. The directory /mnt/data/supervisor/addons/data/de554ef4_bind/cache/ does not exist either, so I am unsure where the cache files are.

The documentation says that the bind add-on runs as a named user. I do not have a named user created on my HA, and the directory owner is set to messagebus:docker. Did I miss something?

**Comment by amnesia033** [comment]
I've figured it out, you have to point the zone file to /config/zones/ and not the /addon_configs/de554ef4_bind/zones/ but then for the love of God, why would you write in the documentation that the zone files are located in /addon_configs/de554ef4_bind/zones/

**Comment by cmsj** [comment]
I'm honestly not really sure what is the best way to describe the paths. It's only `/config/zones` if you're inside the Bind container. If you're using something like the OS level ssh login, it's `/mnt/data/supervisor/addon_configs/de554ef4_bind/zones/` or if you're using an add-on level SSH login it's more likely to be `/addon_configs/de554ef4_bind/zones`.

They're all true, but the context from which you're trying to access the files, makes only one of them true at a time.

As for the `named` user, that is created inside the bind container and is the user that bind runs as, in that container. It's most likely to have a UID of 100 and a GID of 101, which can be used in another context (e.g. via SSH) to control/limit the ownership of the zone files.

I guess the tl;dr here is that there is a lot of subtle UNIX-y stuff going on under the hood and there isn't really an easy way to describe that to people, other than hoping that, like you, they are able to figure it out themselves.

**Comment by amnesia033** [comment]
Thank you. I hope that it makes a lot of lives easer :)
