### ISSUE TITLE
Config files are not accessible from outside

### ISSUE THREAD

**Issue by samnung** [cmsj/addon-bind#4]
Hi, I've just found your addon. I tried to install it to my Home Assistant and I have no idea how to access the config files.

As far as I know the `/data` folder is unique to each addon, so you cannot access it by other addon (VSCode, Terminal, File editor, ...). It would be better to move config files into `addon_config` folder, which should be separate `config` folder for each addon. Or store it in `/config/<slug>`. For more info see https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-advanced-options.

**Comment by cmsj** [comment]
Thanks for the info, that makes a lot of sense. I'll work on changing it.
