### ISSUE TITLE
Loading from master file failed: file not found

### ISSUE THREAD

**Issue by tolopepper** [cmsj/addon-bind#6]
Hello!
I got error:
"06-Jan-2024 18:04:41.742 zone 10.168.192.in-addr.arpa/IN: loading from master file db.rev.10.168.192.in-addr.arpa failed: file not found"

I put zone file into location /addon_configs/de554ef4_bind/zones/db.rev.10.168.192.in-addr.arpa and then edited named.conf:

[...]
zone "10.168.192.in-addr.arpa"
	{
	type master;
	file "db.rev.10.168.192.in-addr.arpa";
	};
[...]

I have tried to change 'file' option in named.conf to full path "/addon_configs/de554ef4_bind/zones/db.rev.10.168.192.in-addr.arpa" and "zones/db.rev.10.168.192.in-addr.arpa" and got the same error.

How to point to zones files properly?

Thank you!

**Comment by ilpincio85** [comment]
you have to point it with /config/zones/
